# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlistapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='bucket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bucketlists', to='bucketlistapi.Bucket'),
            preserve_default=False,
        ),
    ]
