# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlistapi', '0003_review_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='buckelist',
            new_name='bucketlist',
        ),
    ]
